target-version = "py311"
line-length = 120

[lint]
select = ["ALL"]
ignore = [
    # to be compatible with ruff format
    "E501",
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
]

[lint.extend-per-file-ignores]
"__init__.py" = ["D"]
"tests/*" = ["D"]
"examples/*" = ["D"]

fixable = ["ALL"]
unfixable = []


# Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"tests/*" = ["S101"]

[lint.flake8-copyright]
author = "Hikaru Nakashima"

[lint.flake8-annotations]
mypy-init-return = true

[lint.flake8-type-checking]
strict = true

[lint.pydocstyle]
convention = "google"
